name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Because...'
jobs:
  build:
    name: "Build (JDK-${{ matrix.java }}, ${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Download JDK'
        uses: sormuras/download-jdk@v1
        with:
          feature: ${{ matrix.java }}
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: jdkfile
          jdkFile: ${{ env.JDK_FILE }}
      - name: 'Build with Bach'
        shell: bash
        run: |
          PATH=.bach/bin:$PATH
          bach build
      - name: 'Package self-contained Java application'
        shell: bash
        run: |
          jpackage --verbose \
          --name bach+javafx \
          --description "Show-case building a modular Java + JavaFX application with Bach" \
          --vendor "Christian Stein" \
          --runtime-image .bach/workspace/image \
          --module com.github.sormuras.bach.javafx/com.github.sormuras.bach.javafx.Main \
          --dest .bach/workspace/package
      - name: 'Upload packaged application'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ github.sha }}
          path: |
            .bach/workspace/package
