name: build
on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 2 * * 6"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build with Bach.java'
        run: jshell https://bit.do/bach-build
      - name: 'Describe main module'
        run: jar --describe-module --file .bach/modules/main/com.github.sormuras.bach.javafx.jar
      - name: 'Upload build summary'
        uses: actions/upload-artifact@v1
        with:
          name: summary.md
          path: .bach/summary.md
