name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Because...'
jobs:
  build:
    name: "Build (JDK-${{ matrix.java }}, ${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ 22 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 'Set up JDK'
        uses: oracle-actions/setup-java@v1
        with:
          release: ${{ matrix.java }}
      - name: 'Build with Bach'
        run: java --show-version @build
      - name: 'Package self-contained Java application installer'
        shell: bash
        run: |
          jpackage --verbose \
          --name bach-demo-javafx \
          --description "Show-case building a modular Java + JavaFX application with Bach" \
          --vendor "Christian Stein" \
          --runtime-image .bach/out/main/image \
          --module demo/demo.Main \
          --dest .bach/out/main/package
      - name: 'Upload packaged application installer'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ github.sha }}
          path: |
            .bach/out/main/package
